<html lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta name="description" content="The core aim of our project is to create online learning management system that combines best practices in organizing training so that it will be interesting, useful and much easier for the students. The most important part of our project is to fertilize future programmers, showing them that it is not as difficult as it sounds. This will happen through brief and extensive online practical competitions taken their levels, with certificates and prizes for the best ones."/><meta name="author" content="TechEdu++"/><meta name="keywords" content="Learning, Online, System, Presentations, Videos, Exam"/><meta name="distribution" content="web"/><meta name="robots" content="index, follow"/><meta name="google-site-verification" content="eCU54DH_8vQnzWO0Q3fXoQmalvA3rCjiXSH6mZdDgkg"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link rel="icon" href="/favicon.png"/><title>Студентска система :: TechEdu ++</title><link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700"/><link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons"/><link rel="stylesheet" href="/css/bootstrap.min.css"/><link rel="stylesheet" href="/css/bootstrap-material-design.min.css"/><link rel="stylesheet" href="/css/ripples.min.css"/><link rel="stylesheet" href="/css/snackbar.min.css"/><link rel="stylesheet" href="/css/extension.css"/><link href="/css/jumbotron.css" rel="stylesheet"/><meta property="og:url" content="https://www.facebook.com/TechEducationGroup/"/><meta property="og:type" content="website"/><link rel="stylesheet" href="/news/d9757859af.css"/><link rel="stylesheet" href="/node_modules/font-awesome/css/font-awesome.min.css"/><div id="fb-root"></div><script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script><style type="text/css">.col-md-6 {
	width: 49.5%
}
.thumbnail {
	margin-right: 2px;
	padding: 0px;
}
.img-responsive {
	width: 100%;
}
.caption-full {
	border-left: 1px solid #aaa;
	border-bottom: 1px solid #aaa;
	border-right: 1px solid #aaa;
	padding: 4px;
}
</style></head><body><nav class="navbar navbar-static-top navbar-default"><div class="container"><div class="nav-header"><button type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse" class="navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="#" class="navbar-brand">TechEdu ++</a></div><div class="navbar-collapse collapse navbar-responsive-collapse"><ul class="nav navbar-nav"><li><a href="/">Начало</a></li><li><a href="/news">Новини</a></li><li class="active"><a href="#">Компании</a></li><li><a href="https://chat.techedu.cf">Форум</a></li><li><a href="/aboutus.php">За нас</a></li></ul><ul class="nav navbar-nav navbar-right"><li><a href="/login.php"> 
<?php if (isset ($_SESSION["userid"])) { echo $_SESSION["name"]; } else { echo "Login"; } ?> </a></li></ul></div></div></nav><div class="jumbotron"><div class="container"><center><img style="background-color: rgba(0,0,0,0);" src="/img/logo.png"/><h1 class="display-3"><span>We develop new learning methods</span></h1></center></div></div><div class="container"><div id="consentio" class="col-md-6 thumbnail"><img src="https://cdn-images-1.medium.com/max/500/1*_D54lhvvgRh9Z9_XjyE0OA@2x.png" alt="" class="img-responsive"/><div class="caption-full"><h3 class="pull-right">основана 2016г.</h3><p><br/></p><h3>Проекти:</h3><p><div class="panel panel-primary"><div class="panel-heading"><h4>The net.vote platform</h4></div><div class="panel-body"><p>The net.vote platform allows millions of people to express their opinion simultaneously, in a fun, easy and universally understandable way. </p><p>Our clients and partners get real-time insights allowing them to react promptly to the opinion of their customers, clients, stakeholders and audience.</p></div></div><div class="panel panel-primary"><div class="panel-heading"><h4>Свободни позиции</h4></div><div class="panel-body"><ul><li>data scientists</li><li>data viz</li><li>front end devs </li></ul></div></div><div class="panel panel-primary"><div class="panel-heading"><h4>Езици за програмиране</h4></div><div class="panel-body"><p>JavaScript, HTML, Perl, Python, Java, Redis, PostgreSQL, REACT, Node.js</p></div></div><h4>Стажантски програми за ученици: Да</h4><h4> 
Сайт: <a href="https://consent.io">https://consent.io</a></h4></p></div></div><div id="deltabg" class="col-md-6 thumbnail"><img src="https://blog.delta.bg/wp-content/uploads/2016/01/Delta-pic.png" alt="" class="img-responsive"/><div class="caption-full"><h3 class="pull-right">основана 2009г.</h3><p><br/></p><h3>Проекти:</h3><p><div class="panel panel-primary"><div class="panel-heading"><h4>Основна дейност</h4></div><div class="panel-body"><p>Hosting</p><p>Cloud based solutions</p></div></div><div class="panel panel-primary"><div class="panel-heading"><h4>Езици за програмиране</h4></div><div class="panel-body"><p>PHP, Bash, Perl</p></div></div><h4>Стажантски програми за ученици: Да</h4><h4> 
Сайт: <a href="https://delta.bg">https://delta.bg</a></h4></p></div></div></div><footer><div class="container container-holder"><ul class="row"><li class="col-md-3 col-sm-12 col-xs-12 footer-list-wrapper"><h3 class="list-title">TechEdu ++</h3><hr/><ul class="footer-list"><li><a href="/aboutus.php">За нас</a></li><li><a href="/aboutus.php#trainers">Лектори</a></li><li><a href="/aboutus.php#authors">Автори на проекта</a></li></ul></li><li class="col-md-3 col-sm-12 col-xs-12 footer-list-wrapper"><h3 class="list-title">Курсове &amp; Семинари</h3><hr/><ul class="footer-list"><li><a href="/trainings/tracks">Тракове</a></li><li><a href="/trainings/courses">Курсове</a></li><li><a href="/trainings/seminars">Семинари</a></li></ul></li><li class="col-md-3 col-sm-12 col-xs-12 footer-list-wrapper"><h3 class="list-title">Партньори</h3><hr/><ul class="footer-list"><li><a target="_blank" href="https://delta.bg/">Delta.BG</a></li><li><a target="_blank" href="http://www.vrexpress.bg/">VR Express</a></li><li><a target="_blank" href="https://consent.io/">Consent.io</a></li><li><a target="_blank" href="http://www.igreet.co/">iGreet</a></li></ul></li><li class="col-md-3 col-sm-12 col-xs-12 footer-list-wrapper"><ul class="social"><li><a href="https://facebook.com/TechEducationGroup/" target="_blank" class="icon-btn"><span class="fa fa-2x fa-facebook"></span></a></li><li><a href="https://www.youtube.com/channel/UCT1g_MbzP5UJauAqmvNq1aQ" target="_blank" class="icon-btn"><span class="fa fa-2x fa-youtube-play"></span></a></li><li><a href="http://github.com/TechEducationPlusPlus/" target="_blank" class="icon-btn"><span class="fa fa-2x fa-github"></span></a></li></ul><div class="all-rights-reserved"><p>&copy; 2017 TechEdu ++</p><p>Всички права запазени.</p><p> <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/2.5/in/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/2.5/in/88x31.png"/></a></p></div></li></ul></div></footer><script src="/js/jquery.min.js"></script><script src="/js/tether.min.js"></script><script src="/js/bootstrap.min.js"></script><script src="/js/material.min.js"></script><script src="/js/ripples.min.js"></script><script src="/js/snackbar.min.js"></script><script src="/js/jquery.nouislider.min.js"></script><script src="/js/main.js"></script></body></html>