USE	`Infocourse`;
DROP TABLE IF EXISTS `Seminars`;
DROP TABLE IF EXISTS `Tracks`;
DROP TABLE IF EXISTS `Courses`;
DROP TABLE IF EXISTS `Videos`;
DROP TABLE IF EXISTS `Comments`;
DROP TABLE IF EXISTS `Trainers`;
DROP TABLE IF EXISTS `News`;
