('Preparing...', 'PHP1', '/courses/PHP/videos/0', 'https://www.youtube.com/embed/heXKR7KDt-c', 'Author: Yasen Georgiev', '#'),
('Basics', 'PHP1', '/courses/PHP/videos/1', 'https://www.youtube.com/embed/dztfsg2tQDs', 'Author: Yasen Georgiev', '#'),
('Arrays&amp;Conditional Statements - Group A', 'PHP1', '/courses/PHP/videos/2', 'https://www.youtube.com/embed/rKdvAiYdh7I', 'Author: Yasen Georgiev', '#'),
('Arrays&amp;Conditional Statements - Group B', 'PHP1', '/courses/PHP/videos/3', 'https://www.youtube.com/embed/OytP2CQWjvY', 'Author: Yasen Georgiev', '#'),
('Loops<br>Group A', 'PHP1', '/courses/PHP/videos/4', 'https://www.youtube.com/embed/CTziiSKich8', 'Author: Yasen Georgiev', '#'),
('Loops<br>Group B', 'PHP1', '/courses/PHP/videos/5', 'https://www.youtube.com/embed/zWdqNpzOPhw', 'Author: Yasen Georgiev', '#'),
('Loops - Group C', 'PHP1', '/courses/PHP/videos/6', 'https://www.youtube.com/embed/2ldFC-senNE', 'Author: Yasen Georgiev', '#'),
('Live Solving', 'PHP1', '/courses/PHP/videos/7', 'https://www.youtube.com/embed/_J8sFWQKIS4', 'Author: Yasen Georgiev', '#'),
('Hosting. ICN.Bg', 'PHP1', '/courses/PHP/videos/8', 'https://www.youtube.com/embed/ynwybdVp6Nk', 'Author: Yasen Georgiev', '#'),
('Forms<br>Group A', 'PHP1', '/courses/PHP/videos/9', 'https://www.youtube.com/embed/9mn_cnvdBVY', 'Author: Yasen Georgiev', '#'),
('Forms<br>Group B', 'PHP1', '/courses/PHP/videos/10', 'https://www.youtube.com/embed/DeS7xOxywl4', 'Author: Yasen Georgiev', '#'),
('Cookies. Sessions - Group C', 'PHP1', '/courses/PHP/videos/11', 'https://www.youtube.com/embed/9bOBM5Z_Nr0', 'Author: Yasen Georgiev', '#'),
('Exercise<br>Part 1', 'PHP1', '/courses/PHP/videos/12', 'https://www.youtube.com/embed/OQoDRBdSiqc', 'Author: Yasen Georgiev', '#'),
('Exercise<br>Part 2', 'PHP1', '/courses/PHP/videos/13', 'https://www.youtube.com/embed/AS3CUMmTqmI', 'Author: Yasen Georgiev', '#'),
('DataBases<br><br><br>', 'PHP2', '/courses/PHP/videos/14', 'https://www.youtube.com/embed/UCabYNOFUqw', 'Author: Yasen Georgiev', '#'),
('MySQL &amp; phpMyAdmin<br><br><br>', 'PHP2', '/courses/PHP/videos/15', 'https://www.youtube.com/embed/raDNElaW6F', 'Author: Yasen Georgiev', '#'),
('MySQL @ PHP<br><br><br>', 'PHP2', '/courses/PHP/videos/16', 'https://www.youtube.com/embed/MMPMpQEuDT8', 'Author: Yasen Georgiev', '#'),
('Functions. Good Practices<br><br>', 'PHP2', '/courses/PHP/videos/17', 'https://www.youtube.com/embed/2LdLm4oV1Lk', 'Author: Yasen Georgiev', '#'),
('Functions<br><br><br>', 'PHP2', '/courses/PHP/videos/18', 'https://www.youtube.com/embed/Ulix9SAcTxU', 'Author: Yasen Georgiev', '#'),
('OOP basics<br><br><br>', 'PHP2', '/courses/PHP/videos/19', 'https://www.youtube.com/embed/HHXmedW45ms', 'Author: Yasen Georgiev', '#'),
('Inheritance, Magic Methods, Publicity.<br><br>', 'PHP2', '/courses/PHP/videos/20', 'https://www.youtube.com/embed/I4dWkBamRYs', 'Author: Yasen Georgiev', '#'),
('Inheritance, Magic Methods, Publicity. - Group B', 'PHP2', '/courses/PHP/videos/21', 'https://www.youtube.com/embed/XUwyfQ7WTnI', 'Author: Yasen Georgiev', '#'),
('<span style=\"font-size: 0.75em\">Autoloading, namespaces, parent::, Interfaces - Group A</span>', 'PHP2', '/courses/PHP/videos/22', 'https://www.youtube.com/embed/BHkIIzJFti8', 'Author: Yasen Georgiev', '#'),
('<span style=\"font-size: 0.75em\">Autoloading, namespaces, parent::, Interfaces - Group B</span>', 'PHP2', '/courses/PHP/videos/23', 'https://www.youtube.com/embed/_FA0tuK78ik', 'Author: Yasen Georgiev', '#'),
('Exceptions<br><br><br>', 'PHP2', '/courses/PHP/videos/24', 'https://www.youtube.com/embed/Av8VNukyj0U', 'Author: Yasen Georgiev', '#'),
('MVC. Laravel<br><br><br>', 'PHP2', '/courses/PHP/videos/25', 'https://www.youtube.com/embed/t522p2BwZ_g', 'Author: Yasen Georgiev', '#'),
('<span style=\"font-size: 0.69em\">Eloquent ORM. Routing. Middlewares. Views. Blade Templating</span>', 'PHP2', '/courses/PHP/videos/26', 'https://www.youtube.com/embed/fedrAcbCboI', 'Author: Yasen Georgiev', '#'),
('Phonebook - Part 1<br><br><br>', 'PHP2', '/courses/PHP/videos/27', 'https://www.youtube.com/embed/ee-dFlCWKj4', 'Author: Yasen Georgiev', '#'),
('Phonebook - Part 2<br><br><br>', 'PHP2', '/courses/PHP/videos/28', 'https://www.youtube.com/embed/XP3W5XqTrPM', 'Author: Yasen Georgiev', '#'),
('Introduction to C++ (#<span class=\"nvote\" data-return=\"true\">TechEdu Course 1</span>)', 'C++1', '/courses/C++/videos/Introduction+to+C%2b%2b', 'https://www.youtube.com/embed/Ot3Uxh6bZxU', 'Alex Tsvetanov', '#'),
('I/O Stream', 'C++1', '/courses/C++/videos/IO%20Stream', 'https://www.youtube.com/embed/phM0lHrmVnE', 'Alex Tsvetanov', 'https://atj.openjudge.tk/contests/1'),
('Data Types and Variables', 'C++1', '/courses/C++/videos/DataTypesVariables', 'https://www.youtube.com/embed/QCvTRpruM8E', 'Alex Tsvetanov', '#'),
('Overflow, underflow and casting', 'C++1', '/courses/C++/videos/OverUnderCast', 'https://www.youtube.com/embed/zWMbeBmz4EU', 'Alex Tsvetanov', '#'),
('Pointers', 'C++1', '/courses/C++/videos/Pointers', 'https://www.youtube.com/embed/M51p8Rs_4ls', 'Alex Tsvetanov', '#'),
--('if-else', 'C++1', '/courses/C++/videos/if-else', 'https://www.youtube.com/embed/sPV2_eJtgmk', 'Evgeni Vasilev', '#'),
--('switch-case', 'C++1', '/courses/C++/videos/switch', 'https://www.youtube.com/embed/yBxR6FZKl4E', 'Evgeni Vasilev', '#'),
--('while loop', 'C++1', '/courses/C++/videos/while', 'https://www.youtube.com/embed/LFENULP3qeg', 'Evgeni Vasilev', '#'),
--('do-while loop', 'C++1', '/courses/C++/videos/do-while', 'https://www.youtube.com/embed/ji6xvgGmiKc', 'Evgeni Vasilev', '#'),
--('for loop', 'C++1', '/courses/C++/videos/for', 'https://www.youtube.com/embed/QQtZD08-15g', 'Evgeni Vasilev', '#'),
--('break, continue', 'C++1', '/courses/C++/videos/break_continue', 'https://www.youtube.com/embed/FaISNM23cW0', 'Evgeni Vasilev', '#'),
('Sort function', 'C++2', '/courses/C++/videos/sort_func', 'https://www.youtube.com/embed/okiF-XsrSWY', 'Marin Shalamanov', '#'),
('Binary search function', 'C++2', '/courses/C++/videos/binary_search_function', 'https://www.youtube.com/embed/slk-hXnrXF0', 'Marin Shalamanov', '#'),
('lower/upper bound', 'C++2', '/courses/C++/videos/bound_functions', 'https://www.youtube.com/embed/NJJ3CEKHySU', 'Marin Shalamanov', '#'),
('Cube root function', 'C++2', '/courses/C++/videos/cube_root', 'https://www.youtube.com/embed/BtjdITzbvmk', 'Marin Shalamanov', '#'),
('Workshop - sysadmin', 'C++2', '/courses/C++/videos/workshop_sysadmin', 'https://www.youtube.com/embed/vl3cAW2Kq6w', 'Marin Shalamanov', '#'),
('Counting sort', 'SortFind', '/courses/Algorithms/videos/counting_sort', 'https://www.youtube.com/embed/wAPHExxXDjo', 'Marin Shalamanov', '#'),
('Binary search', 'SortFind', '/courses/Algorithms/videos/binary_search', 'https://www.youtube.com/embed/cwmdfliNj5E', 'Marin Shalamanov', '#'),
('Introduction in Graphs', 'Graphs', '/courses/Algorithms/videos/Introduction_to_Graphs', 'https://www.youtube.com/embed/wXv3VEMzEBM', 'Marin Shalamanov', '#'),
('List of neighbours', 'Graphs', '/courses/Algorithms/videos/List_of_neighbours', 'https://www.youtube.com/embed/xqRLrrxjM-U', 'Marin Shalamanov', '#'),
('BFS', 'Graphs', '/courses/Algorithms/videos/BFS', 'https://www.youtube.com/embed/qax90KL-lMk', 'Marin Shalamanov', '#'),
('Min path with BFS', 'Graphs', '/courses/Algorithms/videos/Min_path_in_Graph', 'https://www.youtube.com/embed/igAboBxH4YE', 'Marin Shalamanov', '#'),
('Welcome to TechEdu++', 'Java1', '/courses/Java1/videos/welcome', 'https://www.youtube.com/embed/M3Mr20rfr64', 'Hristo Todorov', '#'),
('Introduction to programming', 'Java1', '/courses/Java1/videos/intro', 'https://www.youtube.com/embed/MKk3b49f1w8', 'Hristo Todorov', '#'),
('DFS', 'Graphs', '/courses/Algorithms/videos/DFS', 'https://www.youtube.com/embed/dSqZZqjoDjA', 'Marin Shalamanov', '#'),
('Introduction to loops', 'C++1', '/courses/C++1/videos/LoopsInto', "https://www.youtube.com/embed/_4Zr66NdjKQ", 'Dobrin Bashev', '#'),
('For, While, Do-while loops', 'C++1', '/courses/C++1/videos/LoopsOperators', "https://www.youtube.com/embed/LZLg2fxbw0s", 'Dobrin Bashev', '#'),
('Nested loops, break/continue', 'C++1', '/courses/C++1/videos/NestedLoops', "https://youtu.be/tLhyoOlhC2E", 'Dobrin Bashev', '#'),
('Loops workhop', 'C++1', '/courses/C++1/videos/LoopsWorkshop', "https://youtu.be/WhCTwXYOF3M", 'Dobrin Bashev', '#')
;
